apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rhtap-chatbot-app-21 
  janus-idp.io/tekton: rhtap-chatbot-app-21
  backstage.io/kubernetes-id: rhtap-chatbot-app-21
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhtap-chatbot-app-21
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml